######################################################################
# Automatically generated by qmake (3.0) lun. sept. 28 12:40:18 2015
######################################################################

TARGET = qpriorityqueue_test
QT += core testlib
INCLUDEPATH += .

# Input
HEADERS += qpriorityqueue.h qpriorityqueue_test.h
SOURCES += qpriorityqueue_test.cpp
